name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend: 
              - 'frontend/**'
      - run: npm install
      - run: CI= npm run build
