name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend: 
              - 'frontend/**'
      - run: npm ci
      - run: npm run build
